# init new day 
# cd into new day 
# create input input_small 
# create part1.ml part2.ml at lib/
new:
	dune init proj day$(day); cd day$(day); touch input input_small; cd lib; touch part1.ml part2.ml
